
namespace MSFSConnector
{
    public enum Units
    {
        Frequency_BCD32,
        inHg,
        ft__min,
        m,
        yard,
        meters_per_second,
        Slugs_per_cubic_foot,
        meter_scaler_256,
        foot,
        nautical_mile,
        percent_over_100,
        percentage,
        fahrenheit,
        kilogram_per_cubic_meter,
        per_second,
        kilogram_meters,
        meter__second,
        in2,
        in3,
        meters_per_second_scaler_256,
        ft2,
        ft3,
        decinmile,
        amperes,
        nice_minutes_per_round,
        Enum,
        farenheit,
        meter_per_second_scaler_256,
        Bco16,
        Slugs_per_cubic_feet,
        feet,
        minutes,
        decibel,
        degree_latitude,
        meters_per_second_squared,
        halfs,
        feet__second,
        pound___force_per_square_foot,
        Slug__ft3,
        kilometer__hour,
        hour_over_10,
        minute_per_round,
        slugs,
        MHz,
        cm,
        sq_cm,
        meters__second,
        Boolean,
        Megahertz,
        km2,
        km3,
        millibar_scaler_16,
        millimeter_of_mercury,
        percent,
        radian_per_second,
        meters_cubed,
        inches,
        pounds_per_hour,
        foot___pounds,
        degrees_per_second_ang16,
        rpms,
        cubic_kilometers,
        radians_per_second,
        slugs_feet_squared,
        newton_meters,
        bar,
        psf_scaler_16k,
        part,
        cu_yd,
        meter_latitude,
        mile,
        meters_per_minute,
        kelvin,
        machs,
        flags,
        seconds,
        psi_scaler_16k,
        per_minute,
        ampere,
        kPa,
        half,
        sq_ft,
        quarts,
        kph,
        fs7_charging_amps,
        geepounds,
        degree,
        kilograms_per_cubic_meter,
        keyframe,
        slug,
        Slug_per_cubic_foot,
        cubic_inches,
        feet__minute,
        mm2,
        mm3,
        days,
        square_inch,
        millimeters_of_water,
        Hz,
        years,
        Slug_per_cubic_feet,
        Hertz,
        thirds,
        millimeter_of_water,
        bel,
        sq_in,
        second,
        day,
        kilometers,
        degrees_per_second,
        millimeters_of_mercury,
        pascals,
        degrees_angl16,
        mmHg,
        m__s,
        knots,
        kilogram_per_second,
        decibels,
        cubic_miles,
        inHg_64_over_64k,
        mph,
        boost_inHg,
        celsius_scaler_1__256,
        foot_per_second_squared,
        hours,
        kg,
        km,
        sq_km,
        decinmiles,
        cmHg,
        millibars,
        times,
        degrees_angl32,
        rankine,
        number,
        square_miles,
        kilogram_force_per_square_centimeter,
        degree_per_second,
        knot_scaler_128,
        newton_meter,
        mach,
        scaler,
        hour,
        mbar,
        square_millimeter,
        atmospheres,
        kilogram_meter,
        position,
        pounds,
        miles,
        third,
        percent_scaler_32k,
        percent_scaler_16k,
        sq_mm,
        m2,
        m3,
        miles_per_hour,
        radians,
        knot,
        centimeters,
        volt,
        square_yard,
        millimeters,
        square_foot,
        kilograms,
        cubic_yards,
        kilometers__hour,
        meters_latitude,
        amps,
        Nm,
        millibars_scaler_16,
        gallon_per_hour,
        cubic_meter,
        feet_per_second,
        round,
        kilogram_meter_squared,
        cu_cm,
        cubic_centimeters,
        meters_scaler_256,
        cubic_millimeters,
        meters,
        minute,
        square_yards,
        mbars,
        square_feet,
        geepound,
        kilograms_meter_squared,
        amp,
        kilopascal,
        liter_per_hour,
        celsius_fs7_egt,
        Frequency_ADF_BCD32,
        square_meter,
        decimiles,
        pounds_scaler_256,
        Pa,
        GForce,
        degree_longitude,
        feet_per_second_squared,
        square_centimeter,
        yards,
        ft___lbs,
        pph,
        gallons,
        inches_of_mercury,
        more_than_a_half,
        meter,
        nice_minute_per_round,
        meter_per_second,
        hectopascal,
        cubic_inch,
        kilograms_per_second,
        cubic_kilometer,
        cu_ft,
        slug_feet_squared,
        square_centimeters,
        cubic_meters,
        square_millimeters,
        pound_per_hour,
        revolution_per_minute,
        minutes_per_round,
        volts,
        square_mile,
        decimile,
        gallon,
        degrees,
        cm2,
        cm3,
        newtons_per_square_meter,
        cu_m,
        celsius_scaler_16k,
        nmiles,
        psf,
        square_inches,
        psi,
        Bool,
        fs7_oil_quantity,
        atmosphere,
        cubic_millimeter,
        Kilohertz,
        feet_per_minute,
        meter_cubed,
        lbf___feet,
        kgf_meters,
        degree_per_second_ang16,
        celsius_scaler_256,
        rpm,
        newton_per_square_meter,
        cu_in,
        pascal,
        per_radian,
        poundal_feet,
        numbers,
        meter_cubed_per_second,
        per_hour,
        psi_4_over_16k,
        foot_pounds,
        meters_cubed_per_second,
        psi_fs7_oil_pressure,
        celsius_fs7_oil_temp,
        atm,
        kilometers_per_hour,
        boost_cmHg,
        yd2,
        position_128,
        yd3,
        cu_km,
        year,
        gallons_per_hour,
        G_Force,
        cubic_yard,
        kilogram,
        meter_per_minute,
        rounds,
        cubic_foot,
        foot_pound,
        boost_psi,
        degree_angl16,
        cubic_centimeter,
        pound_scaler_256,
        cubic_feet,
        nautical_miles,
        foot___pound,
        quart,
        hours_over_10,
        grads,
        cu_mm,
        millimeter,
        hectopascals,
        degrees_latitude,
        G_Force_624_scaled,
        liter,
        sq_yd,
        knots_scaler_128,
        ft_lb_per_second,
        degree_angl32,
        liters,
        grad,
        lbs,
        inch,
        position_32k,
        position_16k,
        bars,
        degrees_longitude,
        mile_per_hour,
        meter_per_second_squared,
        liters_per_hour,
        revolutions_per_minute,
        keyframes,
        centimeter_of_mercury,
        sq_m,
        pound___force_per_square_inch,
        Watt,
        bels,
        angl16,
        KgFSqCm,
        mask,
        rpm_1_over_16k,
        kilometer,
        square_kilometers,
        centimeter,
        cubic_mile,
        Watts,
        celsius,
        ratio,
        centimeters_of_mercury,
        Frequency_BCD16,
        radian,
        per_degree,
        nmile,
        gph,
        square_meters,
        angl32,
        millibar,
        KHz,
        kilometer_per_hour,
        mach_3d2_over_64k,
        kgf_meter,
        percent_scaler_2pow23,
        square_kilometer,
        inch_of_mercury,
    }

    //static public readonly string[] UniqueNames = new string[]
    //      {
    //	"meter",
    //	"centimeter",
    //	"kilometer",
    //	"millimeter",
    //	"mile",
    //	"nmile",
    //	"decinmile",
    //	"foot",
    //	"inch",
    //	"yard",
    //	"meter scaler 256",
    //	"square meter",
    //	"square centimeter",
    //	"square kilometer",
    //	"square millimeter",
    //	"square mile",
    //	"square feet",
    //	"square inch",
    //	"square yard",
    //	"meter cubed",
    //	"liter",
    //	"gallon",
    //	"quart",
    //	"fs7 oil quantity",
    //	"cubic centimeter",
    //	"cubic kilometer",
    //	"cubic millimeter",
    //	"cubic mile",
    //	"cubic feet",
    //	"cubic inch",
    //	"cubic yard",
    //	"kelvin",
    //	"rankine",
    //	"farenheit",
    //	"celsius",
    //	"GLOBALP->eng1.oil_tmp",
    //	"celsius fs7 egt",
    //	"celsius scaler 16k",
    //	"celsius scaler 256",
    //	"celsius scaler 1__256",
    //	"part",
    //	"half",
    //	"third",
    //	"percent",
    //	"percent over 100",
    //	"bel",
    //	"decibel",
    //	"more_than_a_half",
    //	"times",
    //	"ratio",
    //	"number",
    //	"scaler",
    //	"percentage",
    //	"percent scaler 16k",
    //	"percent scaler 32k",
    //	"percent scaler 2pow23",
    //	"position",
    //	"position 32k",
    //	"position 16k",
    //	"position 128",
    //	"keyframe",
    //	"per radian",
    //	"per degree",
    //	"radian",
    //	"round",
    //	"degree",
    //	"grad",
    //	"angl16",
    //	"angl32",
    //	"degree latitude",
    //	"degree longitude",
    //	"meter latitude",
    //	"radian per second",
    //	"revolution per minute",
    //	"minute per round",
    //	"nice minute per round",
    //	"degree per second",
    //	"GLOBALP->delta_heading_rate",
    //	"rpm 1 over 16k",
    //	"meter__second",
    //	"meter per minute",
    //	"feet__second",
    //	"feet__minute",
    //	"kilometer__hour",
    //	"knot",
    //	"mile per hour",
    //	"GLOBALP->vertical_speed",
    //	"knot scaler 128",
    //	"meter per second scaler 256",
    //	"per second",
    //	"per minute",
    //	"per hour",
    //	"mach",
    //	"mach 3d2 over 64k",
    //	"pascal",
    //	"kilopascal",
    //	"kilogram force per square centimeter",
    //	"millimeter of mercury",
    //	"centimeter of mercury",
    //	"inch of mercury",
    //	"atmosphere",
    //	"millimeter of water",
    //	"pound-force per square inch",
    //	"pound-force per square foot",
    //	"bar",
    //	"boost cmHg",
    //	"boost inHg",
    //	"boost psi",
    //	"GLOBALP->eng1.manifold_pressure",
    //	"GLOBALP->eng1.oil_prs",
    //	"psf scaler 16k",
    //	"psi scaler 16k",
    //	"psi 4 over 16k",
    //	"millibar",
    //	"millibar scaler 16",
    //	"second",
    //	"minute",
    //	"hour",
    //	"day",
    //	"hour over 10",
    //	"year",
    //	"Watt",
    //	"ft lb per second",
    //	"meter cubed per second",
    //	"gallon per hour",
    //	"liter per hour",
    //	"kilogram per second",
    //	"pound per hour",
    //	"kilogram",
    //	"pound",
    //	"pound scaler 256",
    //	"slug",
    //	"slug feet squared",
    //	"kilogram meter squared",
    //	"ampere",
    //	"fs7 charging amps",
    //	"volt",
    //	"Hertz",
    //	"Kilohertz",
    //	"Megahertz",
    //	"Frequency BCD32",
    //	"Frequency BCD16",
    //	"Frequency ADF BCD32",
    //	"Enum",
    //	"Bco16",
    //	"mask",
    //	"flags",
    //	"meter per second squared",
    //	"GForce",
    //	"G Force 624 scaled",
    //	"feet per second squared",
    //	"kilogram per cubic meter",
    //	"Slug per cubic feet",
    //	"newton meter",
    //	"foot pound",
    //	"lbf-feet",
    //	"kilogram meter",
    //	"poundal feet",
    //      };
    //  }
}
